server:
  port: 8088

---

spring:
  profiles: default
  cloud:
    gateway:
      routes:
        - id: ecs
          uri: http://localhost:8081
          predicates:
            - Path=/ecs/**
        - id: sample
          uri: http://localhost:8089
          predicates:
            - Path=/sample/**
server:
  port: 8080

logging:
  level:
    root: error   # trace, debug, info, warn, error, fatal
    org:
      springframework:
        cloud: debug
---

spring:
  profiles: docker
  cloud:
    gateway:
      routes:
        - id: payment
          uri: http://payment:8080
          predicates:
            - Path=/payments/**, /callmemleak**
        - id: storage
          uri: http://storage:8080
          predicates:
            - Path=/storages/**, /reviews/**, /check/**
        - id: reservation
          uri: http://reservation:8080
          predicates:
            - Path=/reservations/** 
        - id: message
          uri: http://message:8080
          predicates:
            - Path=/messages/** 
        - id: viewpage
          uri: http://viewpage:8080
          predicates:
            - Path= /storageviews/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true

server:
  port: 8083
